# Generated by Django 5.2.5 on 2025-08-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_servicio_imagen_servicioimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioimagen',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='servicios/videos/'),
        ),
    ]
