# Generated by Django 5.2.5 on 2025-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_servicioimagen_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_preferida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='hora_preferida',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
